import { Appointment, Patient, Doctor, Conversation, LabReport, Bill, PharmacyItem, Shift, OPDQueue, Notification, Message } from './types';

export const mockAppointments: Appointment[] = [
  { id: 'APT001', patientName: 'Sarah Johnson', patientId: 'P001', doctorName: 'Dr. Michael Chen', doctorId: 'D001', department: 'Cardiology', date: '2025-01-15', time: '09:00 AM', duration: 30, status: 'scheduled', type: 'consultation', room: 'Room 201', priority: 'medium', notes: 'Follow-up on hypertension management' },
  { id: 'APT002', patientName: 'James Wilson', patientId: 'P002', doctorName: 'Dr. Emily Roberts', doctorId: 'D002', department: 'Neurology', date: '2025-01-15', time: '09:30 AM', duration: 45, status: 'in-progress', type: 'follow-up', room: 'Room 105', priority: 'high', notes: 'MRI results review' },
  { id: 'APT003', patientName: 'Maria Garcia', patientId: 'P003', doctorName: 'Dr. Michael Chen', doctorId: 'D001', department: 'Cardiology', date: '2025-01-15', time: '10:00 AM', duration: 30, status: 'scheduled', type: 'telemedicine', priority: 'medium' },
  { id: 'APT004', patientName: 'Robert Brown', patientId: 'P004', doctorName: 'Dr. Sarah Kim', doctorId: 'D003', department: 'Orthopedics', date: '2025-01-15', time: '10:30 AM', duration: 30, status: 'completed', type: 'consultation', room: 'Room 302', priority: 'low' },
  { id: 'APT005', patientName: 'Lisa Anderson', patientId: 'P005', doctorName: 'Dr. James Park', doctorId: 'D004', department: 'Pediatrics', date: '2025-01-15', time: '11:00 AM', duration: 30, status: 'scheduled', type: 'follow-up', room: 'Room 108', priority: 'medium' },
  { id: 'APT006', patientName: 'David Martinez', patientId: 'P006', doctorName: 'Dr. Emily Roberts', doctorId: 'D002', department: 'Neurology', date: '2025-01-15', time: '11:30 AM', duration: 30, status: 'cancelled', type: 'consultation', priority: 'low' },
  { id: 'APT007', patientName: 'Emma Thompson', patientId: 'P007', doctorName: 'Dr. Sarah Kim', doctorId: 'D003', department: 'Orthopedics', date: '2025-01-15', time: '02:00 PM', duration: 120, status: 'scheduled', type: 'surgery', room: 'OR-3', priority: 'urgent', notes: 'Knee replacement surgery' },
  { id: 'APT008', patientName: 'William Davis', patientId: 'P008', doctorName: 'Dr. Michael Chen', doctorId: 'D001', department: 'Cardiology', date: '2025-01-16', time: '09:00 AM', duration: 60, status: 'scheduled', type: 'emergency', room: 'ER-1', priority: 'urgent' },
  { id: 'APT009', patientName: 'Jennifer Lee', patientId: 'P009', doctorName: 'Dr. Amanda Foster', doctorId: 'D005', department: 'Dermatology', date: '2025-01-15', time: '03:00 PM', duration: 30, status: 'scheduled', type: 'consultation', room: 'Room 205', priority: 'low' },
  { id: 'APT010', patientName: 'Michael Chang', patientId: 'P010', doctorName: 'Dr. James Park', doctorId: 'D004', department: 'Pediatrics', date: '2025-01-15', time: '04:00 PM', duration: 30, status: 'scheduled', type: 'follow-up', room: 'Room 108', priority: 'medium' },
];

export const mockPatients: Patient[] = [
  { id: 'P001', name: 'Sarah Johnson', age: 45, gender: 'female', phone: '+1 (555) 123-4567', email: 'sarah.j@email.com', bloodGroup: 'A+', address: '123 Oak Street, Springfield, IL 62701', emergencyContact: '+1 (555) 987-6543', conditions: ['Hypertension', 'Type 2 Diabetes'], allergies: ['Penicillin'], medications: ['Lisinopril 10mg', 'Metformin 500mg'], lastVisit: '2025-01-10', status: 'active', insuranceProvider: 'BlueCross BlueShield', insuranceId: 'BC-789456', dateOfBirth: '1980-03-15', weight: 68, height: 165 },
  { id: 'P002', name: 'James Wilson', age: 62, gender: 'male', phone: '+1 (555) 234-5678', email: 'james.w@email.com', bloodGroup: 'O+', address: '456 Elm Avenue, Riverside, CA 92501', emergencyContact: '+1 (555) 876-5432', conditions: ['Coronary Artery Disease', 'Hyperlipidemia', 'Atrial Fibrillation'], allergies: ['Sulfa drugs', 'Aspirin'], medications: ['Atorvastatin 40mg', 'Metoprolol 50mg', 'Warfarin 5mg'], lastVisit: '2025-01-12', status: 'admitted', roomNumber: 'ICU-5', insuranceProvider: 'Aetna', insuranceId: 'AE-456123', dateOfBirth: '1963-07-22', weight: 82, height: 175 },
  { id: 'P003', name: 'Maria Garcia', age: 34, gender: 'female', phone: '+1 (555) 345-6789', email: 'maria.g@email.com', bloodGroup: 'B+', address: '789 Pine Road, Lakewood, CO 80226', emergencyContact: '+1 (555) 765-4321', conditions: ['Asthma', 'Anxiety Disorder'], allergies: ['Latex', 'Shellfish'], medications: ['Albuterol Inhaler', 'Sertraline 50mg'], lastVisit: '2025-01-08', status: 'active', insuranceProvider: 'United Health', insuranceId: 'UH-321654', dateOfBirth: '1991-11-08', weight: 58, height: 160 },
  { id: 'P004', name: 'Robert Brown', age: 55, gender: 'male', phone: '+1 (555) 456-7890', email: 'robert.b@email.com', bloodGroup: 'AB+', address: '321 Maple Drive, Hillcrest, NY 10598', emergencyContact: '+1 (555) 654-3210', conditions: ['Osteoarthritis', 'Hypertension', 'GERD'], allergies: [], medications: ['Ibuprofen 400mg', 'Amlodipine 5mg', 'Omeprazole 20mg'], lastVisit: '2025-01-14', status: 'active', insuranceProvider: 'Cigna', insuranceId: 'CG-654987', dateOfBirth: '1970-05-30', weight: 90, height: 180 },
  { id: 'P005', name: 'Lisa Anderson', age: 8, gender: 'female', phone: '+1 (555) 567-8901', email: 'lisa.parents@email.com', bloodGroup: 'O-', address: '654 Cedar Lane, Brookfield, WI 53005', emergencyContact: '+1 (555) 543-2109', conditions: ['ADHD', 'Mild Asthma'], allergies: ['Peanuts', 'Tree nuts', 'Dairy'], medications: ['Methylphenidate 10mg'], lastVisit: '2025-01-05', status: 'active', insuranceProvider: 'MetLife', insuranceId: 'ML-987321', dateOfBirth: '2017-02-14', weight: 28, height: 125 },
  { id: 'P006', name: 'David Martinez', age: 38, gender: 'male', phone: '+1 (555) 678-9012', email: 'david.m@email.com', bloodGroup: 'A-', address: '987 Birch Court, Meadowbrook, TX 75001', emergencyContact: '+1 (555) 432-1098', conditions: ['Migraine', 'Anxiety', 'Insomnia'], allergies: ['Codeine'], medications: ['Sumatriptan 50mg', 'Lorazepam 1mg'], lastVisit: '2024-12-28', status: 'discharged', insuranceProvider: 'Humana', insuranceId: 'HU-147258', dateOfBirth: '1987-09-12', weight: 75, height: 178 },
  { id: 'P007', name: 'Emma Thompson', age: 52, gender: 'female', phone: '+1 (555) 789-0123', email: 'emma.t@email.com', bloodGroup: 'B-', address: '147 Willow Way, Greenfield, MA 01301', emergencyContact: '+1 (555) 321-0987', conditions: ['Osteoarthritis', 'Hypothyroidism'], allergies: ['Ibuprofen'], medications: ['Levothyroxine 75mcg', 'Acetaminophen 500mg'], lastVisit: '2025-01-13', status: 'active', insuranceProvider: 'Anthem', insuranceId: 'AN-258147', dateOfBirth: '1973-04-18', weight: 72, height: 168 },
  { id: 'P008', name: 'William Davis', age: 68, gender: 'male', phone: '+1 (555) 890-1234', email: 'william.d@email.com', bloodGroup: 'O-', address: '258 Spruce Street, Oakdale, MN 55128', emergencyContact: '+1 (555) 210-9876', conditions: ['Heart Failure', 'COPD', 'Type 2 Diabetes'], allergies: ['Penicillin', 'Morphine'], medications: ['Furosemide 40mg', 'Tiotropium Inhaler', 'Insulin Glargine'], lastVisit: '2025-01-14', status: 'critical', roomNumber: 'CCU-2', insuranceProvider: 'Medicare', insuranceId: 'MC-369258', dateOfBirth: '1957-08-25', weight: 78, height: 172 },
];

export const mockDoctors: Doctor[] = [
  { id: 'D001', name: 'Dr. Michael Chen', specialization: 'Interventional Cardiology', department: 'Cardiology', experience: 15, rating: 4.9, reviewCount: 342, patients: 1240, available: true, phone: '+1 (555) 111-2222', email: 'm.chen@hospiron.com', schedule: 'Mon-Fri 8AM-4PM', consultationFee: 250, qualifications: ['MD - Harvard Medical School', 'FACC', 'Interventional Cardiology Fellowship - Mayo Clinic'], bio: 'Leading expert in interventional cardiology with over 15 years of experience.', languages: ['English', 'Mandarin'] },
  { id: 'D002', name: 'Dr. Emily Roberts', specialization: 'Neurology & Epilepsy', department: 'Neurology', experience: 12, rating: 4.8, reviewCount: 287, patients: 980, available: true, phone: '+1 (555) 222-3333', email: 'e.roberts@hospiron.com', schedule: 'Mon-Thu 9AM-5PM', consultationFee: 300, qualifications: ['MD - Johns Hopkins University', 'FAAN', 'PhD in Neuroscience - Stanford'], bio: 'Specializes in epilepsy management and neurodegenerative disorders.', languages: ['English', 'Spanish'] },
  { id: 'D003', name: 'Dr. Sarah Kim', specialization: 'Sports Medicine & Joint Replacement', department: 'Orthopedics', experience: 10, rating: 4.7, reviewCount: 198, patients: 756, available: false, phone: '+1 (555) 333-4444', email: 's.kim@hospiron.com', schedule: 'Tue-Sat 8AM-3PM', consultationFee: 275, qualifications: ['MD - Stanford University', 'FAAOS', 'Sports Medicine Fellowship - HSS'], bio: 'Expert in minimally invasive joint replacement.', languages: ['English', 'Korean'] },
  { id: 'D004', name: 'Dr. James Park', specialization: 'Pediatric Medicine', department: 'Pediatrics', experience: 8, rating: 4.9, reviewCount: 456, patients: 1580, available: true, phone: '+1 (555) 444-5555', email: 'j.park@hospiron.com', schedule: 'Mon-Fri 7AM-3PM', consultationFee: 200, qualifications: ['MD - Yale School of Medicine', 'FAAP', 'Pediatric Residency - Boston Children\'s Hospital'], bio: 'Passionate about child development and preventive care.', languages: ['English', 'Korean', 'Japanese'] },
  { id: 'D005', name: 'Dr. Amanda Foster', specialization: 'Dermatology & Cosmetic', department: 'Dermatology', experience: 9, rating: 4.6, reviewCount: 523, patients: 2100, available: true, phone: '+1 (555) 555-6666', email: 'a.foster@hospiron.com', schedule: 'Mon-Wed-Fri 9AM-5PM', consultationFee: 225, qualifications: ['MD - Columbia University', 'FAAD', 'Mohs Surgery Certified'], bio: 'Specializes in skin cancer detection and cosmetic dermatology.', languages: ['English', 'French'] },
  { id: 'D006', name: 'Dr. Richard Hayes', specialization: 'General Surgery', department: 'Surgery', experience: 20, rating: 4.8, reviewCount: 678, patients: 3200, available: false, phone: '+1 (555) 666-7777', email: 'r.hayes@hospiron.com', schedule: 'Mon-Fri 6AM-2PM', consultationFee: 350, qualifications: ['MD - UCSF', 'FACS', 'Robotic Surgery Certified'], bio: 'Highly experienced surgeon specializing in minimally invasive procedures.', languages: ['English'] },
];

export const mockConversations: Conversation[] = [
  { id: 'C1', participantName: 'Dr. Michael Chen', participantRole: 'doctor', lastMessage: 'The ECG results look normal. Let\'s schedule a follow-up in 3 months.', lastMessageTime: '10:30 AM', unreadCount: 2, online: true, lastSeen: 'Just now' },
  { id: 'C2', participantName: 'Nurse Patricia Lee', participantRole: 'nurse', lastMessage: 'Patient in Room 205 needs medication refill. BP is stable at 120/80.', lastMessageTime: '09:45 AM', unreadCount: 1, online: true, lastSeen: '2 min ago' },
  { id: 'C3', participantName: 'Dr. Emily Roberts', participantRole: 'doctor', lastMessage: 'Can you review the MRI report for Wilson? There are some concerning findings.', lastMessageTime: '09:15 AM', unreadCount: 0, online: false, lastSeen: '1 hour ago' },
  { id: 'C4', participantName: 'Admin Office', participantRole: 'admin', lastMessage: 'Monthly staff meeting rescheduled to Friday 3PM.', lastMessageTime: 'Yesterday', unreadCount: 0, online: false, lastSeen: 'Yesterday' },
  { id: 'C5', participantName: 'Lab Department', participantRole: 'nurse', lastMessage: 'Blood work results for Garcia are ready. All values within normal range.', lastMessageTime: 'Yesterday', unreadCount: 3, online: true, lastSeen: '5 min ago' },
  { id: 'C6', participantName: 'Pharmacy', participantRole: 'nurse', lastMessage: 'New stock of Amoxicillin 500mg arrived. 450 units available.', lastMessageTime: '2 days ago', unreadCount: 0, online: false, lastSeen: '2 days ago' },
];

export const mockMessages: Message[] = [
  { id: 'M1', senderId: 'D001', senderName: 'Dr. Michael Chen', senderRole: 'doctor', content: 'Good morning! I\'ve reviewed Sarah Johnson\'s latest test results.', timestamp: '10:15 AM', read: true, conversationId: 'C1' },
  { id: 'M2', senderId: 'D001', senderName: 'Dr. Michael Chen', senderRole: 'doctor', content: 'Her cholesterol levels have improved significantly since starting the new medication. LDL down from 180 to 145.', timestamp: '10:18 AM', read: true, conversationId: 'C1' },
  { id: 'M3', senderId: 'me', senderName: 'Me', senderRole: 'admin', content: 'That\'s great news! Should we adjust the dosage or continue with current regimen?', timestamp: '10:22 AM', read: true, conversationId: 'C1' },
  { id: 'M4', senderId: 'D001', senderName: 'Dr. Michael Chen', senderRole: 'doctor', content: 'I think we can maintain the current dosage for now. Let\'s reassess in 3 months with another lipid panel.', timestamp: '10:25 AM', read: true, conversationId: 'C1' },
  { id: 'M5', senderId: 'D001', senderName: 'Dr. Michael Chen', senderRole: 'doctor', content: 'The ECG results look normal. Let\'s schedule a follow-up in 3 months.', timestamp: '10:30 AM', read: false, conversationId: 'C1' },
  { id: 'M6', senderId: 'D001', senderName: 'Dr. Michael Chen', senderRole: 'doctor', content: 'Also, please remind her about the dietary restrictions we discussed. Low sodium, low saturated fat.', timestamp: '10:30 AM', read: false, conversationId: 'C1' },
];

export const mockLabReports: LabReport[] = [
  { id: 'L1', patientName: 'Sarah Johnson', patientId: 'P001', testName: 'Complete Blood Count (CBC)', category: 'blood', date: '2025-01-14', status: 'completed', result: 'WBC: 7.2, RBC: 4.8, Hgb: 14.2, Hct: 42%, Plt: 250', normalRange: 'WBC: 4.5-11.0, RBC: 4.5-5.5, Hgb: 12-16', doctorName: 'Dr. Michael Chen', priority: 'normal', technicianName: 'Mark Wilson', sampleId: 'SMP-2025-001' },
  { id: 'L2', patientName: 'James Wilson', patientId: 'P002', testName: 'Lipid Panel', category: 'blood', date: '2025-01-14', status: 'completed', result: 'Total Cholesterol: 245 mg/dL, LDL: 165, HDL: 45, Triglycerides: 180', normalRange: 'Total: <200, LDL: <100, HDL: >60', doctorName: 'Dr. Emily Roberts', notes: 'LDL elevated - consider statin adjustment', priority: 'urgent', technicianName: 'Sarah Miller', sampleId: 'SMP-2025-002' },
  { id: 'L3', patientName: 'Maria Garcia', patientId: 'P003', testName: 'Chest X-Ray', category: 'imaging', date: '2025-01-13', status: 'completed', result: 'No abnormalities detected. Clear lung fields.', doctorName: 'Dr. Michael Chen', priority: 'normal', technicianName: 'John Davis' },
  { id: 'L4', patientName: 'Robert Brown', patientId: 'P004', testName: 'MRI - Left Knee', category: 'imaging', date: '2025-01-15', status: 'in-progress', doctorName: 'Dr. Sarah Kim', priority: 'normal', technicianName: 'Amy Chen' },
  { id: 'L5', patientName: 'James Wilson', patientId: 'P002', testName: 'Troponin I', category: 'cardiology', date: '2025-01-15', status: 'pending', doctorName: 'Dr. Michael Chen', priority: 'critical', sampleId: 'SMP-2025-005' },
  { id: 'L6', patientName: 'Lisa Anderson', patientId: 'P005', testName: 'Allergy Panel', category: 'pathology', date: '2025-01-12', status: 'completed', result: 'Positive: Peanuts (Class 4), Tree nuts (Class 3), Dust mites (Class 2)', doctorName: 'Dr. James Park', priority: 'normal', technicianName: 'Rachel Kim', sampleId: 'SMP-2025-006' },
  { id: 'L7', patientName: 'David Martinez', patientId: 'P006', testName: 'Urinalysis', category: 'urine', date: '2025-01-11', status: 'completed', result: 'Normal - no abnormalities. pH: 6.0, SG: 1.020', doctorName: 'Dr. Emily Roberts', priority: 'normal', technicianName: 'Mark Wilson', sampleId: 'SMP-2025-007' },
  { id: 'L8', patientName: 'Emma Thompson', patientId: 'P007', testName: 'Thyroid Function Panel', category: 'blood', date: '2025-01-14', status: 'completed', result: 'TSH: 2.8, Free T4: 1.2, Free T3: 3.1', normalRange: 'TSH: 0.4-4.0, Free T4: 0.8-1.8', doctorName: 'Dr. Amanda Foster', priority: 'normal', sampleId: 'SMP-2025-008' },
];

export const mockBills: Bill[] = [
  { id: 'INV-2025-001', patientName: 'Sarah Johnson', patientId: 'P001', date: '2025-01-14', dueDate: '2025-02-14', items: [{ id: '1', description: 'Cardiology Consultation', category: 'Consultation', quantity: 1, unitPrice: 250, total: 250 }, { id: '2', description: 'Blood Work - CBC', category: 'Lab', quantity: 1, unitPrice: 85, total: 85 }, { id: '3', description: 'ECG', category: 'Diagnostic', quantity: 1, unitPrice: 120, total: 120 }], subtotal: 455, tax: 36.4, discount: 0, total: 491.4, status: 'paid', paymentMethod: 'Insurance', insuranceClaim: true, insuranceAmount: 393.12, patientAmount: 98.28 },
  { id: 'INV-2025-002', patientName: 'James Wilson', patientId: 'P002', date: '2025-01-15', dueDate: '2025-02-15', items: [{ id: '1', description: 'ICU Room (3 days)', category: 'Room', quantity: 3, unitPrice: 1500, total: 4500 }, { id: '2', description: 'Medications', category: 'Pharmacy', quantity: 1, unitPrice: 850, total: 850 }, { id: '3', description: 'Lab Tests', category: 'Lab', quantity: 4, unitPrice: 125, total: 500 }, { id: '4', description: 'Cardiologist Consult', category: 'Consultation', quantity: 2, unitPrice: 300, total: 600 }], subtotal: 6450, tax: 516, discount: 200, total: 6766, status: 'pending', insuranceClaim: true, insuranceAmount: 5412.8, patientAmount: 1353.2 },
  { id: 'INV-2025-003', patientName: 'Maria Garcia', patientId: 'P003', date: '2025-01-13', dueDate: '2025-02-13', items: [{ id: '1', description: 'Telemedicine Consultation', category: 'Consultation', quantity: 1, unitPrice: 150, total: 150 }, { id: '2', description: 'Chest X-Ray', category: 'Imaging', quantity: 1, unitPrice: 200, total: 200 }], subtotal: 350, tax: 28, discount: 0, total: 378, status: 'paid', paymentMethod: 'Credit Card' },
  { id: 'INV-2025-004', patientName: 'Robert Brown', patientId: 'P004', date: '2025-01-15', dueDate: '2025-01-30', items: [{ id: '1', description: 'Orthopedic Consultation', category: 'Consultation', quantity: 1, unitPrice: 275, total: 275 }, { id: '2', description: 'MRI - Knee', category: 'Imaging', quantity: 1, unitPrice: 1200, total: 1200 }, { id: '3', description: 'Physical Therapy (4 sessions)', category: 'Therapy', quantity: 4, unitPrice: 150, total: 600 }], subtotal: 2075, tax: 166, discount: 100, total: 2141, status: 'overdue', insuranceClaim: false },
];

export const mockPharmacy: PharmacyItem[] = [
  { id: 'PH1', name: 'Amoxicillin 500mg', genericName: 'Amoxicillin', category: 'Antibiotics', stock: 450, minStock: 100, price: 12.99, manufacturer: 'Pfizer', expiryDate: '2026-06-15', prescription: true, dosage: '500mg 3x daily for 7-10 days', sideEffects: ['Nausea', 'Diarrhea', 'Rash'] },
  { id: 'PH2', name: 'Metformin 850mg', genericName: 'Metformin HCl', category: 'Diabetes', stock: 320, minStock: 150, price: 8.50, manufacturer: 'Merck', expiryDate: '2025-12-30', prescription: true, dosage: '850mg 2x daily with meals', sideEffects: ['GI upset', 'Lactic acidosis (rare)'] },
  { id: 'PH3', name: 'Lisinopril 10mg', genericName: 'Lisinopril', category: 'Cardiovascular', stock: 280, minStock: 100, price: 15.75, manufacturer: 'AstraZeneca', expiryDate: '2026-03-20', prescription: true, dosage: '10mg once daily', sideEffects: ['Dizziness', 'Cough', 'Hyperkalemia'] },
  { id: 'PH4', name: 'Ibuprofen 400mg', genericName: 'Ibuprofen', category: 'Pain Relief', stock: 800, minStock: 200, price: 5.99, manufacturer: 'Johnson & Johnson', expiryDate: '2026-09-10', prescription: false, dosage: '400mg every 6 hours as needed', sideEffects: ['GI irritation'] },
  { id: 'PH5', name: 'Omeprazole 20mg', genericName: 'Omeprazole', category: 'Gastrointestinal', stock: 150, minStock: 80, price: 11.25, manufacturer: 'Novartis', expiryDate: '2025-08-15', prescription: true, dosage: '20mg before breakfast', sideEffects: ['Headache', 'Diarrhea'] },
  { id: 'PH6', name: 'Salbutamol Inhaler', genericName: 'Albuterol', category: 'Respiratory', stock: 95, minStock: 50, price: 22.50, manufacturer: 'GSK', expiryDate: '2026-01-30', prescription: true, dosage: '2 puffs as needed', sideEffects: ['Tremor', 'Tachycardia'] },
  { id: 'PH7', name: 'Paracetamol 500mg', genericName: 'Acetaminophen', category: 'Pain Relief', stock: 1200, minStock: 300, price: 3.99, manufacturer: 'Bayer', expiryDate: '2027-02-28', prescription: false, dosage: '500mg every 6 hours, max 4g/day', sideEffects: ['Liver toxicity (overdose)'] },
  { id: 'PH8', name: 'Atorvastatin 40mg', genericName: 'Atorvastatin', category: 'Cardiovascular', stock: 5, minStock: 100, price: 18.90, manufacturer: 'Pfizer', expiryDate: '2025-11-15', prescription: true, dosage: '40mg at bedtime', sideEffects: ['Muscle pain', 'Liver enzyme elevation'] },
];

export const mockShifts: Shift[] = [
  { id: 'S1', staffName: 'Nurse Patricia Lee', staffRole: 'Nurse', department: 'ICU', date: '2025-01-15', startTime: '07:00', endTime: '19:00', status: 'active', hours: 12, notes: 'Senior nurse on duty' },
  { id: 'S2', staffName: 'Nurse John Davis', staffRole: 'Nurse', department: 'Emergency', date: '2025-01-15', startTime: '07:00', endTime: '19:00', status: 'active', hours: 12 },
  { id: 'S3', staffName: 'Nurse Amy Chen', staffRole: 'Nurse', department: 'Pediatrics', date: '2025-01-15', startTime: '19:00', endTime: '07:00', status: 'scheduled', hours: 12 },
  { id: 'S4', staffName: 'Dr. Michael Chen', staffRole: 'Doctor', department: 'Cardiology', date: '2025-01-15', startTime: '08:00', endTime: '16:00', status: 'active', hours: 8 },
  { id: 'S5', staffName: 'Nurse Rachel Kim', staffRole: 'Nurse', department: 'Surgery', date: '2025-01-15', startTime: '07:00', endTime: '19:00', status: 'completed', hours: 12 },
  { id: 'S6', staffName: 'Technician Mark Wilson', staffRole: 'Lab Tech', department: 'Laboratory', date: '2025-01-15', startTime: '06:00', endTime: '14:00', status: 'active', hours: 8 },
];

export const mockOPDQueue: OPDQueue[] = [
  { id: 'O1', tokenNumber: 1, patientName: 'Sarah Johnson', patientId: 'P001', doctorName: 'Dr. Michael Chen', department: 'Cardiology', status: 'completed', waitTime: 0, registeredAt: '08:00 AM', priority: 'normal' },
  { id: 'O2', tokenNumber: 2, patientName: 'James Wilson', patientId: 'P002', doctorName: 'Dr. Emily Roberts', department: 'Neurology', status: 'in-consultation', waitTime: 5, registeredAt: '08:15 AM', priority: 'priority' },
  { id: 'O3', tokenNumber: 3, patientName: 'Maria Garcia', patientId: 'P003', doctorName: 'Dr. Michael Chen', department: 'Cardiology', status: 'waiting', waitTime: 25, registeredAt: '08:30 AM', priority: 'normal' },
  { id: 'O4', tokenNumber: 4, patientName: 'Robert Brown', patientId: 'P004', doctorName: 'Dr. Sarah Kim', department: 'Orthopedics', status: 'waiting', waitTime: 40, registeredAt: '08:45 AM', priority: 'normal' },
  { id: 'O5', tokenNumber: 5, patientName: 'Lisa Anderson', patientId: 'P005', doctorName: 'Dr. James Park', department: 'Pediatrics', status: 'waiting', waitTime: 55, registeredAt: '09:00 AM', priority: 'normal' },
  { id: 'O6', tokenNumber: 6, patientName: 'David Martinez', patientId: 'P006', doctorName: 'Dr. Emily Roberts', department: 'Neurology', status: 'waiting', waitTime: 70, registeredAt: '09:15 AM', priority: 'normal' },
  { id: 'O7', tokenNumber: 7, patientName: 'Emma Thompson', patientId: 'P007', doctorName: 'Dr. Sarah Kim', department: 'Orthopedics', status: 'waiting', waitTime: 85, registeredAt: '09:30 AM', priority: 'priority' },
];

export const mockNotifications: Notification[] = [
  { id: 'N1', title: 'New Appointment', body: 'Sarah Johnson scheduled for Jan 15 at 9:00 AM with Dr. Chen', type: 'appointment', timestamp: '5 min ago', read: false, priority: 'medium' },
  { id: 'N2', title: 'Lab Results Ready', body: 'Blood work results for James Wilson are now available', type: 'lab', timestamp: '15 min ago', read: false, priority: 'high' },
  { id: 'N3', title: 'Payment Received', body: 'Payment of $491.40 received from Sarah Johnson', type: 'billing', timestamp: '1 hour ago', read: false, priority: 'low' },
  { id: 'N4', title: 'New Message', body: 'Dr. Emily Roberts sent you a message about MRI results', type: 'message', timestamp: '2 hours ago', read: true, priority: 'medium' },
  { id: 'N5', title: 'System Update', body: 'Scheduled maintenance tonight from 2:00 AM to 4:00 AM', type: 'system', timestamp: '5 hours ago', read: true, priority: 'low' },
  { id: 'N6', title: 'Critical Alert', body: 'Patient William Davis in CCU-2 requires immediate attention', type: 'alert', timestamp: '10 min ago', read: false, priority: 'high' },
];

export const dashboardStats = {
  todayAppointments: 48,
  patientsAdmitted: 23,
  availableBeds: 67,
  totalBeds: 90,
  totalRevenue: 125430,
  opdWaiting: 12,
  surgeriesToday: 3,
  emergencyCases: 2,
  staffOnDuty: 45,
  occupancyRate: 78,
  avgWaitTime: 18,
  satisfaction: 94,
};
